# Site settings
title: Pillar Blogs
email: sales@pillartechnology.com
description: > # this means to ignore newlines until "baseurl:"
  Pillar to the people!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pillartechnology.github.io" # the base hostname & protocol for your site
twitter_username: agilesoftware
github_username:  PillarTechnology

# Build settings
markdown: kramdown
